pipelines:
  branches:
    develop:
      - step:
          deployment: develop
          script:
            - pipe: atlassian/sftp-deploy:0.5.6
              variables:
                USER: 'bibucket'
                SERVER: 'ns382468.ip-46-105-99.eu'
                REMOTE_PATH: '/home/docker/edwards/tavi/wp-content/themes/tavi-today-theme/'